spring.application.name=backend
# Database Supabase
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.aahlexnbogcvhixirjoy
spring.datasource.password=Mahjoub!@2006

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Port
server.port=8090